name: CPPLint Check

on:
  push:
    paths:
      - 'Attendance.cpp'
  pull_request:
    paths:
      - 'Attendance.cpp'

jobs:
  cpplint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Use the appropriate Python version

    - name: Install cpplint
      run: pip install cpplint

    - name: Run cpplint
      run: |
        cpplint \
          --linelength=120 \
          --filter=-build/include_subdir, \
          +whitespace/indent, \
          +whitespace/tabs, \
          +whitespace/braces, \
          +whitespace/newline, \
          +whitespace/operators, \
          +whitespace/comments \
          --recursive \
          --exclude=directory_to_exclude/*.cpp \
          attendance.cpp
